### ISSUE TITLE
Ubunt Bionic

### ISSUE THREAD

**Issue by elgamal2020** [cri-o/cri-o-ansible#28]
ansible-playbook -i ../hosts.yml cri-o.yml -u ubuntu

PLAY [all] **********************************************************************************************************************************************************************************

TASK [Gathering Facts] **********************************************************************************************************************************************************************
ok: [10.20.100.31]

TASK [Update all in Ubuntu] *****************************************************************************************************************************************************************

changed: [10.20.100.31]

TASK [update all in RHEL/CentOS] ************************************************************************************************************************************************************
skipping: [10.20.100.31]

TASK [Update all packages on Fedora] ********************************************************************************************************************************************************
skipping: [10.20.100.31]

TASK [Install k8s repository key (Ubuntu)] **************************************************************************************************************************************************
changed: [10.20.100.31]

TASK [Install k8s repository (Ubuntu)] ******************************************************************************************************************************************************
fatal: [10.20.100.31]: FAILED! => {"changed": false, "msg": "E:The repository 'http://apt.kubernetes.io kubernetes-bionic Release' does not have a Release file."}
        to retry, use: --limit @/home/ubuntu/cri-o-ansible/cri-o.retry

PLAY RECAP **********************************************************************************************************************************************************************************
10.20.100.31               : ok=3    changed=2    unreachable=0    failed=1

ubuntu@inst:~/cri-o-ansible$
ubuntu@inst:~/cri-o-ansible$
ubuntu@inst:~/cri-o-ansible$
ubuntu@inst:~/cri-o-ansible$ ansible-playbook -i ../hosts.yml cri-o.yml -u ubuntu

PLAY [all] **********************************************************************************************************************************************************************************

TASK [Gathering Facts] **********************************************************************************************************************************************************************
ok: [10.20.100.31]

TASK [Update all in Ubuntu] *****************************************************************************************************************************************************************
ok: [10.20.100.31]

TASK [update all in RHEL/CentOS] ************************************************************************************************************************************************************
skipping: [10.20.100.31]

TASK [Update all packages on Fedora] ********************************************************************************************************************************************************
skipping: [10.20.100.31]

TASK [Install k8s repository key (Ubuntu)] **************************************************************************************************************************************************
^C [ERROR]: User interrupted execution

Process WorkerProcess-5:
Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/local/lib/python3.6/dist-packages/ansible/executor/process/worker.py", line 118, in run
    self._final_q
  File "/usr/local/lib/python3.6/dist-packages/ansible/executor/task_executor.py", line 140, in run
    res = self._execute()
  File "/usr/local/lib/python3.6/dist-packages/ansible/executor/task_executor.py", line 612, in _execute
    result = self._handler.run(task_vars=variables)
  File "/usr/local/lib/python3.6/dist-packages/ansible/plugins/action/normal.py", line 46, in run
    result = merge_hash(result, self._execute_module(task_vars=task_vars, wrap_async=wrap_async))
  File "/usr/local/lib/python3.6/dist-packages/ansible/plugins/action/__init__.py", line 756, in _execute_module
    (module_style, shebang, module_data, module_path) = self._configure_module(module_name=module_name, module_args=module_args, task_vars=task_vars)
  File "/usr/local/lib/python3.6/dist-packages/ansible/plugins/action/__init__.py", line 178, in _configure_module
    environment=final_environment)
  File "/usr/local/lib/python3.6/dist-packages/ansible/executor/module_common.py", line 973, in modify_module
    environment=environment)
  File "/usr/local/lib/python3.6/dist-packages/ansible/executor/module_common.py", line 791, in _find_module_utils
    recursive_finder(module_name, b_module_data, py_module_names, py_module_cache, zf)
  File "/usr/local/lib/python3.6/dist-packages/ansible/executor/module_common.py", line 680, in recursive_finder
    recursive_finder(py_module_file, py_module_cache[py_module_file][0], py_module_names, py_module_cache, zf)
  File "/usr/local/lib/python3.6/dist-packages/ansible/executor/module_common.py", line 540, in recursive_finder
    finder.visit(tree)
  File "/usr/lib/python3.6/ast.py", line 253, in visit
    return visitor(node)
  File "/usr/lib/python3.6/ast.py", line 261, in generic_visit
    self.visit(item)
  File "/usr/lib/python3.6/ast.py", line 253, in visit
    return visitor(node)
  File "/usr/lib/python3.6/ast.py", line 261, in generic_visit
    self.visit(item)
  File "/usr/lib/python3.6/ast.py", line 253, in visit
    return visitor(node)
  File "/usr/lib/python3.6/ast.py", line 261, in generic_visit
    self.visit(item)
  File "/usr/lib/python3.6/ast.py", line 252, in visit
    visitor = getattr(self, method, self.generic_visit)
KeyboardInterrupt
ubuntu@inst:~/cri-o-ansible$ ansible-playbook -v -i ../hosts.yml cri-o.yml -u ubuntu
No config file found; using defaults
/home/ubuntu/hosts.yml did not meet host_list requirements, check plugin documentation if this is unexpected
/home/ubuntu/hosts.yml did not meet script requirements, check plugin documentation if this is unexpected

PLAY [all] **********************************************************************************************************************************************************************************

TASK [Gathering Facts] **********************************************************************************************************************************************************************
ok: [10.20.100.31]

TASK [Update all in Ubuntu] *****************************************************************************************************************************************************************
ok: [10.20.100.31] => {"changed": false, "msg": "Reading package lists...\nBuilding dependency tree...\nReading state information...\nCalculating upgrade...\nThe following package was automatically installed and is no longer required:\n  grub-pc-bin\nUse 'sudo apt autoremove' to remove it.\n0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.\n", "stderr": "", "stderr_lines": [], "stdout": "Reading package lists...\nBuilding dependency tree...\nReading state information...\nCalculating upgrade...\nThe following package was automatically installed and is no longer required:\n  grub-pc-bin\nUse 'sudo apt autoremove' to remove it.\n0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.\n", "stdout_lines": ["Reading package lists...", "Building dependency tree...", "Reading state information...", "Calculating upgrade...", "The following package was automatically installed and is no longer required:", "  grub-pc-bin", "Use 'sudo apt autoremove' to remove it.", "0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded."]}

TASK [update all in RHEL/CentOS] ************************************************************************************************************************************************************
skipping: [10.20.100.31] => {"changed": false, "skip_reason": "Conditional result was False"}

TASK [Update all packages on Fedora] ********************************************************************************************************************************************************
skipping: [10.20.100.31] => {"changed": false, "skip_reason": "Conditional result was False"}

TASK [Install k8s repository key (Ubuntu)] **************************************************************************************************************************************************
ok: [10.20.100.31] => {"changed": false}

TASK [Install k8s repository (Ubuntu)] ******************************************************************************************************************************************************
ok: [10.20.100.31] => {"changed": false, "repo": "deb http://apt.kubernetes.io/ kubernetes-bionic main", "state": "present"}

TASK [Update apt (Ubuntu)] ******************************************************************************************************************************************************************
fatal: [10.20.100.31]: FAILED! => {"changed": false, "msg": "Failed to update apt cache: W:Updating from such a repository can't be done securely, and is therefore disabled by default., W:See apt-secure(8) manpage for repository creation and user configuration details., E:The repository 'http://apt.kubernetes.io kubernetes-bionic Release' does not have a Release file."}
        to retry, use: --limit @/home/ubuntu/cri-o-ansible/cri-o.retry

PLAY RECAP **********************************************************************************************************************************************************************************
10.20.100.31               : ok=4    changed=0    unreachable=0    failed=1

**Comment by hswong3i** [comment]
I have a solution here with Ubuntu 18.04/19.10/20.04 and CentOS/RHEL 7/8 and openSUSE 15.1 support which you may interested in: https://github.com/alvistack/ansible-role-cri_o
